version: 0.2

  phases: 
    install:
      runtime-versions:
        nodejs: 12
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
#       #commands:
#     pre_build:
#       commands:
#         - 'npm install'
#     build: 
#       commands:
#       - 'npm run build'
#     post_build:
#       commands:
#         - 'npm run start'
#   artifacts:
#     #base-directory: strapi
#     base-directory: addo-strapi-blueprint
#     files:        
#         - '**/*'    
#     discard-paths: yes
