version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: "./"
  name: strapi-build
  discard-paths: no
#       #commands:
#     pre_build:
#       commands:
#         - 'npm install'
#     build: 
#       commands:
#       - 'npm run build'
#     post_build:
#       commands:
#         - 'npm run start'
#   artifacts:
#     #base-directory: strapi
#     base-directory: addo-strapi-blueprint
#     files:        
#         - '**/*'    
#     discard-paths: yes
